### ISSUE TITLE
在从天境世界回主世界后，打开箱子就会报错，一个板条箱中有神金矿石（耐酸铝的稿子的词条），位于打完了阿索斯，没打盖亚的状态，以下是连续三次的报错记录

### ISSUE THREAD

**Issue by SCP3856** [TCreopargh/GreedyCraft-CF#1]
[crash-2021-01-25_23.35.13-client.txt](https://github.com/TCreopargh/GreedyCraft-CF/files/5867738/crash-2021-01-25_23.35.13-client.txt)
[crash-2021-01-25_23.38.18-client.txt](https://github.com/TCreopargh/GreedyCraft-CF/files/5867741/crash-2021-01-25_23.38.18-client.txt)
[crash-2021-01-25_23.40.54-client.txt](https://github.com/TCreopargh/GreedyCraft-CF/files/5867742/crash-2021-01-25_23.40.54-client.txt)

**Comment by SCP3856** [comment]
同时，将百科全书调成植物魔法词典也将造成闪退

**Comment by TCreopargh** [comment]
请重启游戏
